site_name: MO | Medarbejder & Organisation
site_url: ""
use_directory_urls: False
site_description: OS2mo dokumentation
repo_name: os2mo
# TODO: Use the GitHub repo when it's ready
repo_url: https://github.com/OS2mo/os2mo
docs_dir: src/

nav:
  - Hjem:
      - index.md
      - home/manual.md
      - home/landscape.md
  - Funktionalitet:
      - features/auditlog.md
      - features/email-notifikationer.md
      - features/stillingsbetegnelser.md
      - features/indplacering-af-it-brugere.md
      - features/insights.md
      - features/klassifikationer.md
      - features/kle.md
      - features/lederhaandtering.md
      - features/med-organisation.md
      - features/org-chart.md
      - features/org-sammenkobling.md
      - features/reports.md
  - Integrationer:
      - Active Directory:
        - integrations/ldap_ad_amqp_integration.md
        - integrations/ad.md
      - integrations/sql_export.md
      - integrations/emus.md
      - integrations/fkk.md
      - integrations/os2sync.md
      - LOS / OPUS:
        - integrations/aarhus-los.md
        - integrations/opusloen.md
      - integrations/omada.md
      - integrations/os2rollekatalog.md
      - integrations/plan2learn.md
      - integrations/safetynet.md
      - SD:
        - integrations/sd-laes.md
        - integrations/sd-skriv.md
        - integrations/sdtoolplus.md
        - integrations/organisationsopmaerkning.md
      - integrations/os2phonebook.md
  - "Implementering & Drift":
      - moaas/index.md
      - moaas/cloud.md
      - moaas/on-prem.md
      - moaas/implementeringsguide.md
  - Teknisk dokumentation:
      # - Understanding bitemporality: TODO
      - tech-docs/architecture.md
      - tech-docs/audit-log.md
      - tech-docs/development.md
      - tech-docs/events.md
      - tech-docs/facets.md
      - GraphQL / API:
          - tech-docs/graphql/intro.md
          - tech-docs/graphql/reads.md
          # - tech-docs/graphql/pagination.md: TODO
          - tech-docs/graphql/migration.md
      - IAM (Identity & Access Management - Keycloak):
          - tech-docs/iam/auth.md
          - tech-docs/iam/rbac.md
          - tech-docs/iam/adfs-setup.md
          - tech-docs/iam/adfs-rbac-setup.md
      # - tech-docs/integration-best-practice.md: TODO
      - Legacy:
        - tech-docs/legacy/lora-objects.md
        - tech-docs/legacy/lora-wildcards.md
        - tech-docs/legacy/amqp.md
        - tech-docs/legacy/triggers.md
        - tech-docs/legacy/log-haendelse-rfc.md
        - tech-docs/legacy/dipex-tools.md
        - tech-docs/legacy/data-import-tool.md

  - Versionshistorik: changelog.md
theme:
  name: "material"
  palette:
    - scheme:
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
  features:
    - navigation.top
    - navigation.tabs
  favicon: static/favicon.ico

# Adds Magenta's colour scheme
extra_css:
  - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.magiclink
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      toc_depth: 3
      permalink: "#"
